# Generated by Django 5.1.6 on 2025-09-06 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse_ligne1', models.CharField(max_length=255)),
                ('adresse_ligne2', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(default='Tunisie', max_length=100)),
                ('newsletter', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('token_suivi', models.CharField(blank=True, max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Commande invité',
                'verbose_name_plural': 'Commandes invités',
            },
        ),
        migrations.CreateModel(
            name='AdresseUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom pour identifier cette adresse', max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nom_famille', models.CharField(max_length=100)),
                ('adresse_ligne1', models.CharField(max_length=255)),
                ('adresse_ligne2', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(default='Tunisie', max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('type_adresse', models.CharField(choices=[('livraison', 'Livraison'), ('facturation', 'Facturation'), ('both', 'Livraison et Facturation')], default='livraison', max_length=20)),
                ('par_defaut', models.BooleanField(default=False, help_text='Adresse par défaut')),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse utilisateur',
                'verbose_name_plural': 'Adresses utilisateurs',
                'ordering': ['-par_defaut', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('newsletter', models.BooleanField(default=False, verbose_name="S'abonner à la newsletter")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
