# Generated by Django 5.1.6 on 2025-08-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('site_web', models.URLField(blank=True)),
                ('contact_principal', models.CharField(blank=True, max_length=100)),
                ('conditions_paiement', models.CharField(blank=True, max_length=200)),
                ('delai_livraison', models.PositiveIntegerField(blank=True, help_text='Délai de livraison en jours', null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence unique du produit', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='boutique.fournisseur'),
        ),
    ]
