# Generated by Django 5.1.6 on 2025-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_fournisseur_produit_reference_alter_produit_sku_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='categorie',
            name='icone',
            field=models.CharField(blank=True, help_text='Classe CSS Font Awesome', max_length=50),
        ),
        migrations.AddField(
            model_name='categorie',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='categorie',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
