# Generated by Django 5.0 on 2025-08-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_alter_categorie_options_categorie_icone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='meta_keywords',
        ),
    ]
